server:
  port: 3081
spring:
  application:
    name: DemotApplication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1X2.16X.X.6X:3306/upload_demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/db1?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: XXXXXX
    #password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  profiles:
    active: mapper.service
  redis:
    host: 1XX.XXX.X.XX
    port: 6379
    #password
    database: 1
